[package]
name = "spacetop"
version = "0.1.0"
edition = "2024"
default-run = "spacetop"

[workspace]
members = [".", "utils/spacelauncher", "utils/spacetop-config", "utils/spacesettings"]
default-members = ["."]
resolver = "3"

[dependencies]
anyhow = "1"
ash = { version = "0.38", default-features = false, features = ["loaded", "std"] }
calloop = "0.14"
evdev = "0.13"
glam = "0.33"
half = "2"
image = { version = "0.25", default-features = false, features = ["exr"] }
naga = { version = "29", features = ["wgsl-in", "spv-out"] }
openxr = { version = "0.22", default-features = false, features = ["loaded"] }
smithay = { version = "0.7.0", default-features = false, features = ["desktop", "wayland_frontend", "renderer_gl", "backend_gbm", "backend_gbm_has_create_with_modifiers2", "backend_gbm_has_fd_for_plane", "xwayland"] }
spacetop-config = { path = "utils/spacetop-config" }

[dev-dependencies]
tempfile = "3"
toml = "0.8"
wayland-client = "0.31"
wayland-protocols = { version = "0.32", features = ["client"] }
